language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: XvcZ5M0TrCiJFKY4NV2KBURBhyL2ctA+0xmkOs0P6SLjemIq7AU+BYxt2nmO3OTY7bI4Mx4yYfdWUIosLI6LMTAmQAskna6EeKCQehqdPFKXHg2mMWLMFPXWaThG6zY5dfKnClHfx3ektp67Q8Els8N/5gy6iZPwdeIgEZIDAHnuZjYYx8x7dV8Vz5XDCCInBn9Z66EIi7p0o9XxIekjTLqvwl6nH8bxadE3KmxLSPm++oGyWo8149Cfx7/qhr/elJ0I/EeR1xvfqHan4eSx5hHWJuFoMy+uwtlnxmZnHQxd3VnPLuMJr/HzIgYDarsPa6Smg825X4zDZB118pVVdgEkXkDmIjJhGQsKXCPe290YHLc0GRxRGyBwLfV20OggpQ4gQ+lEOWMYaioPvZP51C70qIsW0772476TUz6wuB6aHSsQsm9wFNys7aSHzlXWyzKwOuDPLwbp1pkp6p8PspIeVBXFJewKnw1p4EeBg/rtpj+xP25P5l2MoTpVEz/sPfyTWF1/1MhCa5NQU11dAblhwSvgNXtFLYEBZ27wdi+ETFe+X21CmDAKNP03dzr3gBbJ2DFSmpjlVqCKWrHAR8DDxUyH0VO5ozlaR9VMglAwUGqX11sYkjS1d6rYs1s5z/YK62DxkGxbvAv+3iAGiJrAzLX0bZl8aC9uEcP6Cwo=
  app: calm-reef-62318
  on:
    repo: CraigPounds/node-shopping-list-integration-tests
